# research_task:
#   description: >
#     Obtenha as últimas notícias relevantes da empresa Palantir Technologies. Seu ticket é PLTR.
#   expected_output: >
#     Um relatório com as últimas notícias da empresa Palantir Technologies.
#   agent: research_analyst_agent

research_task:
  description: >
    Collect and summarize recent news articles, press
    releases, and market analyses related to the stock and
    its industry.
    Pay special attention to any significant events, market
    sentiments, and analysts' opinions. Also include upcoming 
    events like earnings and others.

    Your final answer MUST be a report that includes a
    comprehensive summary of the latest news, any notable
    shifts in market sentiment, and potential impacts on 
    the stock.
    Also make sure to return the stock ticker.

    {TipSection}

    Make sure to use the most recent data as possible.

    Selected company by the customer: {Company}
  expected_output: >
    A very detailed summary of information related to the company {Company}.
  agent: research_analyst_agent

financial_analysis_task:
  description: >
    Conduct a thorough analysis of the stock's financial
    health and market performance. 
    This includes examining key financial metrics such as
    P/E ratio, EPS growth, revenue trends, and 
    debt-to-equity ratio. 
    Also, analyze the stock's performance in comparison 
    to its industry peers and overall market trends.

    Your final report MUST expand on the summary provided
    but now including a clear assessment of the stock's
    financial standing, its strengths and weaknesses, 
    and how it fares against its competitors in the current
    market scenario.
    Make sure to use the most recent data possible.

    {TipSection}

    {PreviousSummary}
  expected_output: > 
    A complete analysis of the financial situation of the shares
    market health and performance in relation to company {Company}.
  agent: financial_analyst_agent

filings_analysis_task:
  description: >
    Analyze the latest 10-Q and 10-K filings from EDGAR for
    the stock in question. 
    Focus on key sections like Management's Discussion and
    Analysis, financial statements, insider trading activity, 
    and any disclosed risks.
    Extract relevant data and insights that could influence
    the stock's future performance.

    Your final answer must be an expanded report that now
    also highlights significant findings from these filings,
    including any red flags or positive indicators for
    your customer.

    {TipSection}
    
    {PreviousSummary}
  expected_output: > 
    An Analysis of EDGAR's Latest 10-Q and 10-K Filings for the stock in question
  agent: financial_analyst_agent

recommend_task:
  description: >
    Review and synthesize the analyses provided by the
    Financial Analyst and the Research Analyst.
    Combine these insights to form a comprehensive
    investment recommendation. 
    
    You MUST Consider all aspects, including financial
    health, market sentiment, and qualitative data from
    EDGAR filings.

    Make sure to include a section that shows insider 
    trading activity, and upcoming events like earnings.

    Your final answer MUST be a recommendation for your
    customer. It should be a full super detailed report, providing a 
    clear investment stance and strategy with supporting evidence.
    Make it pretty and well formatted for your customer.

    {TipSection}
    
    {PreviousSummary}
  expected_output: >
    A detailed investment recommendation about the company in question.

  agent: investment_advisor_agent
